# Generated by Django 3.1 on 2020-08-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_ip', models.GenericIPAddressField(default='192.168.0.1')),
                ('reported', models.BooleanField(default=False)),
                ('date_checked', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
