# Generated by Django 3.1 on 2020-09-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_ip_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='abuseibdb_payload',
            field=models.TextField(default='No data available'),
        ),
        migrations.AddField(
            model_name='ip',
            name='badips_payload',
            field=models.TextField(default='No data available'),
        ),
        migrations.AddField(
            model_name='ip',
            name='virustotal_payload',
            field=models.TextField(default='No data available'),
        ),
    ]
