# Generated by Django 3.1 on 2020-09-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20200903_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='virustotal_votes_payload',
            field=models.TextField(default='No data avaible'),
        ),
    ]
