# Generated by Django 3.1 on 2020-09-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_ip_virustotal_votes_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='abuseibdb_payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='ip',
            name='badips_payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='ip',
            name='virustotal_payload',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='ip',
            name='virustotal_votes_payload',
            field=models.JSONField(default=dict),
        ),
    ]
