# Generated by Django 3.1 on 2020-09-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_auto_20200909_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='shodan_all_banners_payload',
            field=models.TextField(default='No data available'),
        ),
        migrations.AddField(
            model_name='ip',
            name='shodan_general_info_payload',
            field=models.TextField(default='No data available'),
        ),
    ]
