# Generated by Django 3.1 on 2020-09-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='user',
            new_name='member',
        ),
    ]
